### ISSUE TITLE
自动添加空格后，保持光标在行内的相对位置，而不是绝对位置不变

### ISSUE THREAD

**Issue by tinyoceans** [Natumsol/obsidian-pangu#1]
Hi @Natumsol，非常感谢您实现这个插件。

目前，在执行 `Ctrl + s` 实现自动添加空格后，光标会保持在行内的绝对位置（列数）不变（如 gif 所示，当执行 `Ctrl + s`，光标会停在第二个 english 的 s 和 h 之间）。请问是否能够增加一个设置，使得自动添加空格后，光标在行内的相对位置不变，即仍保持在“测试”之后？

谢谢！

![bug202104032](https://user-images.githubusercontent.com/81858182/113477689-26bfe100-94b6-11eb-890f-543af750bbbc.gif)

**Comment by Natumsol** [comment]
嗯，好的，本周我抽空fix下~

**Comment by Natumsol** [comment]
@tinyoceans Fixed，使用最新版 v1.2.1 版本即可：https://github.com/Natumsol/obsidian-pangu/releases/tag/v1.2.1

![2021-04-12 13-26-06 2021-04-12 13_27_13](https://user-images.githubusercontent.com/6970196/114345086-a70bd380-9b93-11eb-8401-5efe7d943dd2.gif)

**Comment by tinyoceans** [comment]
@Natumsol ，非常感谢更新！

但我发现在最新的 Obsidian v0.11.13 中，插件好像不能够通过 `Ctrl + s` 触发自动添加空格的功能了，可能因为新版 Obsidian 修改了一些接口。我在一个新建的 Obsidian vault 上测试了 obsidian-pangu v1.2.1 和 v1.2.0，发现都有这个问题，另外我也没有找到其他自动添加空格的方式。

这个问题还需要麻烦您解决哈！谢谢！
