### ISSUE TITLE
链接中存在中英文混排时也会自动加空格

### ISSUE THREAD

**Issue by imhgy** [Natumsol/obsidian-pangu#11]
![image](https://user-images.githubusercontent.com/44602901/134806211-ad9840f5-15a6-4f99-88ec-d3254d5ea435.png)
如果链接中存在中英文混排的时候也会添加空格，导致链接失效。

**Comment by LoneFireBlossom** [comment]
希望能改进这个问题，要不然不敢用了😭

**Comment by Natumsol** [comment]
> 希望能改进这个问题，要不然不敢用了😭

嗯，本周末解决

**Comment by Natumsol** [comment]
fixed in version 1.3.4
@imhgy @LoneFireBlossom

**Comment by Awyugan** [comment]
啊，这个问题还是没解决啊。是上传文档有问题吗？[[]]链接里的内容还是会加空格
