### ISSUE TITLE
the note_name in [[note_name]] may be affected and produces a broken link pointing to the note "note_name"

### ISSUE THREAD

**Issue by zhao414** [Natumsol/obsidian-pangu#14]
![image](https://user-images.githubusercontent.com/15528506/151133408-5384e567-4a01-4a66-ab46-b126737f25d1.png)

the note-name between [[]] should be protected and kept unchanged. Otherwise, the link is broken.

**Comment by Natumsol** [comment]
@zhao414 重构之后的[ 1.4.0 ](https://github.com/Natumsol/obsidian-pangu/releases/tag/1.4.0) 版本已修复此问题，have a try !

**Comment by Natumsol** [comment]
#18
