### ISSUE TITLE
markdown 链接开头的行，会在执行盘古后在行首增加一个空格

### ISSUE THREAD

**Issue by willtse** [Natumsol/obsidian-pangu#15]
- 执行盘古前
![image](https://user-images.githubusercontent.com/328654/153135170-7a92c65f-8bd0-4906-ab38-1d1ef5d3edeb.png)

- 执行盘古后
![image](https://user-images.githubusercontent.com/328654/153135194-4e681159-f4e5-4717-8d94-a089f1019de7.png)

---

![image](https://user-images.githubusercontent.com/328654/153135537-85598479-571c-45b1-8c3a-a82c66c3b8e3.png)

执行后在三个地方加入了空格，但是**第5行的空格**不是我想要的，会导致文件内容的**折叠缩进**都出现问题，这个是 feature 还是 bug 呢？可以关闭这个不...

**Comment by Natumsol** [comment]
@willtse  重构之后的[ 1.4.0 ](https://github.com/Natumsol/obsidian-pangu/releases/tag/1.4.0) 版本已修复此问题，have a try !
