### ISSUE TITLE
行内代码带冒号会在最后一个冒号处添加空格 

### ISSUE THREAD

**Issue by mumudm** [Natumsol/obsidian-pangu#16]
## 当前问题
- before
 `sf:::ff`
- after
 `sf::: ff`

## 期望值
行内代码不添加空格

**Comment by Natumsol** [comment]
@mumudm 重构之后的[ 1.4.0 ](https://github.com/Natumsol/obsidian-pangu/releases/tag/1.4.0) 版本已修复此问题，have a try !
