### ISSUE TITLE
执行后会将双向链接里的文字也会增加空格

### ISSUE THREAD

**Issue by Zolliner** [Natumsol/obsidian-pangu#18]
双向链接里引用的文档里有中英文，因此执行后会增加空格，导致无法链接到原有的文档。
虽然可以把文档名称手动增加空格来解决这个问题，但还是希望能够自动识别双向链接[[]]。
感谢

**Comment by Natumsol** [comment]
重构之后的[ 1.4.0 ](https://github.com/Natumsol/obsidian-pangu/releases/tag/1.4.0) 版本已修复此问题，have a try !
