### ISSUE TITLE
与 Obsidian v0.11.13 兼容性问题

### ISSUE THREAD

**Issue by tinyoceans** [Natumsol/obsidian-pangu#2]
Hi @Natumsol，感谢更新！

我发现在最新的 Obsidian v0.11.13 中，插件好像不能够通过 Ctrl + s 触发自动添加空格的功能了，可能因为新版 Obsidian 修改了一些接口。我在一个新建的 Obsidian vault 上测试了 obsidian-pangu v1.2.1 和 v1.2.0，发现都有这个问题，另外我也没有找到其他自动添加空格的方式。

希望您可以解决该问题，谢谢！

**Comment by tinyoceans** [comment]
刚刚发现 `Ctrl + p` 输入"盘古"命令回车即可触发自动添加空格。只是触发命令好像不能绑定到 `Ctrl + s` 了。

再次感谢~

**Comment by Natumsol** [comment]
快捷键 `Ctrl + S` 和 `Command + S`和系统快捷键冲突了，现改为：
Mac : `Shift + Command + S` 
Windows: `Shift + Ctrl + S`
