### ISSUE TITLE
代码片段被增加了空格

### ISSUE THREAD

**Issue by kailanyue** [Natumsol/obsidian-pangu#22]
`std::cmp::Eq`   格式化之后变成   `std:: cmp:: Eq`
 `std::cmp::PartialEq`  格式化之后变成    `std:: cmp:: PartialEq`

情况同 https://github.com/Natumsol/obsidian-pangu/issues/17

**Comment by Natumsol** [comment]
重构之后的[ 1.4.0 ](https://github.com/Natumsol/obsidian-pangu/releases/tag/1.4.0) 版本已修复此问题，have a try !
