### ISSUE TITLE
感谢的伟大及分享

### ISSUE THREAD

**Issue by taohuadaoxiaoyao** [Natumsol/obsidian-pangu#23]
1. 首先感谢大佬的无私分享，目前已经成为我必装的插件了
2. 目前使用过程的遇到的问题，提一个小小的建议。在双链格式中的文件名称也会被自动加上空格，导致双链失效。望大佬能在百忙之中修复一下该问题。具体情况如下：[[mybatis基础7种标签]] 在自动格式化后[[mybatis 基础 7 中标签]]。由于链接的是文件名称，导致链接失效
3. 再次感谢开源作者的伟大

**Comment by Natumsol** [comment]
@taohuadaoxiaoyao 重构之后的[ 1.4.0 ](https://github.com/Natumsol/obsidian-pangu/releases/tag/1.4.0) 版本已修复此问题，have a try !
