### ISSUE TITLE
可否支持在 yaml 块和正文块之间加空行

### ISSUE THREAD

**Issue by Yubuxin** [Natumsol/obsidian-pangu#24]
如题。

**Comment by lianzhehua** [comment]
> 如题。
可以用Linter插件，功能稳定且丰富
[https://github.com/platers/obsidian-linter](https://github.com/platers/obsidian-linter)

**Comment by lianzhehua** [comment]
可以用Linter插件 ，稳定，功能非常丰富

[https://github.com/platers/obsidian-linter](https://github.com/platers/obsidian-linter)

**Comment by Natumsol** [comment]
@Yubuxin 核心功能已用 prettier 重构，重构后的[ 1.4.0 ](https://github.com/Natumsol/obsidian-pangu/releases/tag/1.4.0)应该能解决你的问题，have a try !
