### ISSUE TITLE
转用Linter，功能丰富且稳定。感谢过去一段时间pangu的陪伴

### ISSUE THREAD

**Issue by lianzhehua** [Natumsol/obsidian-pangu#26]
[https://github.com/platers/obsidian-linter](https://github.com/platers/obsidian-linter)

**Comment by lianzhehua** [comment]
[https://github.com/platers/obsidian-linter](https://github.com/platers/obsidian-linter)

**Comment by Natumsol** [comment]
重构之后的[ 1.4.0 ](https://github.com/Natumsol/obsidian-pangu/releases/tag/1.4.0)已修复绝大多数问题，have a try !
