### ISSUE TITLE
在一行内，只要有超链接，超链接之后的中英文混排都无法自动添加空格

### ISSUE THREAD

**Issue by dutry** [Natumsol/obsidian-pangu#27]
例子：
```
关于这个MathJax的问题，在 [官方论坛也有讨论](https://forum.obsidian.md/t/latex-math-newline-line-break/13321) ，却一直没修复。一个折中的办法是，对多行的latex代码
```
上述语句，因为有超链接，超链接前面的中英混排（MathJax）可以成功添加空格，而之后的（latex）则不行

**Comment by Natumsol** [comment]
重构之后的[ 1.4.0 ](https://github.com/Natumsol/obsidian-pangu/releases/tag/1.4.0)已修复，have a try !
