### ISSUE TITLE
FR 能否增加英文的命令控制

### ISSUE THREAD

**Issue by zhao414** [Natumsol/obsidian-pangu#28]
在 command pane中，盘古的命令是需要切换到中文输入法才能调用的。
可否增加一个英文的调用，例如 PanGu，之类。

要不找命令太麻烦了。

实不相瞒，每次重装插件，我都会怀疑是不是插件没装上，因为要好久才回忆起来这个插件的调用命令是中文的。  ：D

**Comment by Natumsol** [comment]
安排！

**Comment by Natumsol** [comment]
更新到 1.5.0 试试。
![image](https://user-images.githubusercontent.com/6970196/201860229-160a38bf-7164-4753-b11b-3cffb7589f98.png)
