### ISSUE TITLE
引用文件名不包含空格的笔记文件时，引用链接被错误的加上了空格

### ISSUE THREAD

**Issue by bitxinyu** [Natumsol/obsidian-pangu#29]
hi，
A笔记标题包含中英文，在被B引用的时候， B中的笔记链接因为加空格无法准确链接到A笔记。
由于旧笔记比较多，不方便一个个修改，所以能否加个功能，笔记的引用链接里中英文之间不自动加空格。

**Comment by Natumsol** [comment]
升级到最新版 1.4.1 试试。

**Comment by bitxinyu** [comment]
> 升级到最新版 1.4.1 试试。

感谢，升级后确实修复了
