### ISSUE TITLE
格式化后列表缩进丢失

### ISSUE THREAD

**Issue by linking2014** [Natumsol/obsidian-pangu#30]
```
1. 111
    - [ ] 123
    - [ ] 222
2. 222
    1. 333
    2. 123
3. 333
```
这样的结构，经过盘古格式化之后，（打开live preview的状态下）看上去缩进就不对了，

格式化前：
![image](https://user-images.githubusercontent.com/8596179/202349729-2dee9420-4188-4df4-958f-015ca2fd67fb.png)

格式化后：
![image](https://user-images.githubusercontent.com/8596179/202349836-bcd04350-6a0d-4b7f-ad9e-a8fef4f67542.png)

**Comment by Natumsol** [comment]
默认 tabWidth 为 2 个空格，你需要的是 4个空格， 更新到最新版，按需配置即可：

![image](https://user-images.githubusercontent.com/6970196/202385382-9cbb6f3b-705a-4243-a294-f77976197e4a.png)
