### ISSUE TITLE
恳请作者能优化一下代码块的处理🙏

### ISSUE THREAD

**Issue by Nshcn** [Natumsol/obsidian-pangu#7]
盘古插件对我这种强迫症患者真的太棒了，万分感谢作者这么棒的插件。

但是有一个地方，希望作者能否优化一下代码块中的处理呢？考虑设置一个ignore选项排除掉对代码块的处理。因为我发现我之前写的不少能运行的代码用盘古处理添加空格后导致一些地方无法正常运行得到预期的结果了。我觉得可能其他人也会遇到这种情况，希望作者大大能优化一下，万分感谢🙏

**Comment by Natumsol** [comment]
可否提供一个「格式化前」 和 「格式化后」的案例？ @Nshcn

**Comment by Nshcn** [comment]
> 可否提供一个「格式化前」 和 「格式化后」的案例？ @Nshcn

我的代码是 vue.js 的代码，格式化之前的 `v-on:click` 在格式化之后会变成 `v-on: click` ，冒号后面会多出一个空格，造成语法错误，无法绑定事件。下面是一个测试用例。

```html
<!DOCTYPE html>
<html>
<body>
<div id="app">
  <!-- 下面这一行格式化后会出现语法错误-->
  <button v-on:click="btnClick">按钮</button>
</div>

<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script type="text/javascript">
  const app = new Vue({
    el: '#app',
    methods: {
      btnClick: function () {
		  console.log('test');
	  },
    }
  })
</script>
</body>
</html>
```

**Comment by Nshcn** [comment]
这是另一个例子，下面的css代码，在进行格式化处理后`0 -1px`会变成`0-1px`
```css
div{
    margin: 0 -1px;
    /* 格式化后变成 0-1px，两个参数之间的空格没了*/
}
```

**Comment by Natumsol** [comment]
@Nshcn  fixed in version 1.3.0.
