### ISSUE TITLE
有序列表的格式化问题

### ISSUE THREAD

**Issue by drrrMikado** [Natumsol/obsidian-pangu#9]
根据这段代码：
https://github.com/Natumsol/obsidian-pangu/blob/34490952d2cb5fc8ca1a809ff301671001573686/formatUtil.ts#L200-L201
可以看到有序列表，格式化后，中间会有两个空格。下面是情况说明：

<table><thead><tr><th>格式化前</th><th>格式化后</th></tr></thead>
<tbody><tr>
<td>

```md
1.<space>pangu1
2.<space>pangu2
```

</td><td>

```markdown
1.<space><space>pangu1
2.<space><space>pangu2
```

</td></tr></tbody></table>

这是为什么这样处理呢？如果可以希望能和无序列表一样，保持一个空格。

**Comment by qazxcdswe123** [comment]
可以在`.obsidian\plugins\obsidian-pangu\main.js`注释掉第194行，但之前被改过的内容得手动改回来

**Comment by drrrMikado** [comment]
> 可以在`.obsidian\plugins\obsidian-pangu\main.js`注释掉第194行，但之前被改过的内容得手动改回来

Thanks
